dblp:
  url: https://dblp.org/search/publ/api?q={}&format=json&h=1000
  topics:
    - "many-task%20optimization"
    - "manytask%20optimization"
    - "multi-task%20optimization"
    - "multitasking%20optimization"

serp:
    topics:
        # allintitle: optimization "many-task" OR "multitask" OR "multitasking" OR "multi-task" -learning
        - "allintitle: optimization \"many-task\" OR \"multitask\" OR \"multitasking\" OR \"multi-task\" -learning"

channel: "serp" # within [serp, dblp]
cache_path: "cached"
readme_path: "README.md"