name: Run Watcher

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"
  push:
    branches: [main]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Shanghai"
      RUN_ENV: "prod" # within ['prod', 'dev']
      SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
      SERP_API_KEY_ZYY: ${{ secrets.SERP_API_KEY_ZYY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run watcher
        run: |
          python setup.py --mode=${{ env.RUN_ENV }} run

      - name: Setup GIT user
        uses: fregante/setup-git-user@v1

      - name: Push done work
        run: |
          git diff --exit-code || git commit -am "Automated deployment @ $(date '+%Y-%m-%d %H:%M:%S') ${{ env.TZ }}"
          git push --force origin main

      - name: Create an issue for new papers
        if: ${{ env.MSG != '' }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/issue-template.md